<a href="https://colab.research.google.com/github/mostafah76/DeepLearning/blob/master/activation_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

activation function in Deep learning
https://keras.io/api/layers/activations/

In [ ]:
# TensorFlow and tf.keras
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

To test your installation, print their version

In [ ]:
print(keras.__version__)

2.2.4-tf


In [ ]:
model = keras.models.Sequential()

In [ ]:
model.add(keras.layers.Flatten(input_shape=(28, 28)))

In [ ]:
model.add(keras.layers.Dense(128, activation='relu'))

In [ ]:
from keras import activations

Using TensorFlow backend.


In [ ]:
model.add(keras.layers.Dense(128, activation=activations.relu))

# relu

tf.keras.activations.relu(x, alpha=0.0, max_value=None, threshold=0)
x: Input
alpha:governs the slope for values lower than the threshold
max_value: sets the saturation threshold (the largest value the function will return)
threshold: threshold value of the activation function below which values will be damped or set to zero

In [ ]:
xx=activations.relu(30.0, alpha=0.0, max_value=None, threshold=0)

In [ ]:
xx

<tf.Tensor: shape=(), dtype=float32, numpy=30.0>

# sigmoid

In [ ]:
model.add(keras.layers.Dense(128, activation=activations.sigmoid))

In [ ]:
xx=activations.sigmoid(-4.0)

In [ ]:
xx

<tf.Tensor: shape=(), dtype=float32, numpy=0.01798621>

In [ ]:
import tensorflow as tf

In [ ]:
a = tf.constant([-20, -1.0, 0.0, 1.0, 20], dtype = tf.float32)
b = tf.keras.activations.sigmoid(a)
b.numpy()

array([2.0611537e-09, 2.6894143e-01, 5.0000000e-01, 7.3105860e-01,
       1.0000000e+00], dtype=float32)

# tanh

Hyperbolic tangent activation function

In [ ]:
a = tf.constant([-3.0,-1.0, 0.0,1.0,3.0], dtype = tf.float32)
b = tf.keras.activations.tanh(a)
b.numpy()

array([-0.9950547, -0.7615942,  0.       ,  0.7615942,  0.9950547],
      dtype=float32)

In [ ]:
model.add(keras.layers.Dense(10, activation=activations.tanh))

# softmax

Softmax converts a real vector to a vector of categorical probabilities.

The elements of the output vector are in range (0, 1) and sum to 1.

Each vector is handled independently. The axis argument sets which axis of the input the function is applied along.

Softmax is often used as the activation for the last layer of a classification network because the result could be interpreted as a probability distribution.

The softmax of each vector x is computed as exp(x) / tf.reduce_sum(exp(x))

In [ ]:
x = tf.constant([[2,5,7]], dtype = tf.float32)

In [ ]:
xx = tf.keras.activations.softmax(x, axis=-1)

In [ ]:
xx

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.00589975, 0.11849965, 0.8756006 ]], dtype=float32)>

# softplus

Softplus activation function, softplus(x) = log(exp(x) + 1)

In [ ]:
xx = tf.keras.activations.softplus(1.0)

In [ ]:
xx

# softsign

Softsign activation function, softsign(x) = x / (abs(x) + 1)

In [ ]:
a = tf.constant([-1.0, 0.0, 1.0], dtype = tf.float32)
b = tf.keras.activations.softsign(a)
b.numpy()

# selu

# elu

# exponential

In [ ]:
model.add(keras.layers.Dense(5, activation=activations.selu))

In [ ]:
model.add(keras.layers.Dense(3, activation=activations.elu))

In [ ]:
model.add(keras.layers.Dense(3, activation=activations.exponential))